language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
deploy:
 provider: heroku
 api_key: 60bd2bd5-64de-49a0-a025-cc458f656cec
 app: fierce-wildwood-87197
 run: "rake db:migrate"
 on:
  all_branches: true